apiVersion: v1
kind: Service
metadata:
  name: job-portal-backend-service
spec:
  selector:
    app: job-portal-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer

