name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Install dependencies
    - name: Install Python Dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    # Step 4: Run Unit Tests
    - name: Run Unit Tests
      working-directory: ./backend
      run: |
        pytest

    # Step 5: Set up Docker Buildx (optional, good for cross-platform)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Step 6: Build Docker image
    - name: Build Docker Image
      run: |
        docker build -t stenny1710/job-portal:latest .

    # Step 7: Log in to Docker Hub and Push
    - name: Log in to Docker Hub and Push Image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
        docker push stenny1710/job-portal:latest
