name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pytest

      # Step 4: Run unit tests
      - name: Run Unit Tests
        run: |
          pytest backend/tests

      # (Optional) Step 5: Upload test results or coverage report
      # - name: Upload test coverage report
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: test-report
      #     path: path/to/report

